# Use the official Python image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY trade_xm_app ./app
COPY tests ./tests

# Expose the port the trade_xm_app runs on
EXPOSE 8000

# Command to run the application (default)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
